from refspy.book import Book
from refspy.library import Library

# See README.md for Library ID numbers
# Spanish uses: https://catholic-resources.org/Bible/Abbreviations-Abreviaciones.htm 
#
# TODO: NC 01/03/2025: Verify.
#
# Based on user submission. Incomplete and untested. Refspy developer (eukras) does not speak Spanish.
#
# QUESTIONS:
# - Does Spanish match refs without accents? e.g. Ex not Éx?
# - Is there a style guide like SBL in English that is definitive for all practical purposes? 

OT = Library(
    id=200,
    name="Antiguo Testamento",
    abbrev="AT",
    books=[
        Book(
            id=1,
            name="Génesis",
            abbrev="Gén",
            aliases=["Gé", "Gn"],
            chapters=50,
        ),
        Book(
            id=2,
            name="Éxodo",
            abbrev="Éxod",
            aliases=["Éx"],
            chapters=40,
        ),
        Book(
            id=3,
            name="Levítico",
            abbrev="Lev",
            aliases=["Le", "Lv"],
            chapters=27,
        ),
        Book(
            id=4,
            name="Números",
            abbrev="Núm",
            aliases=["Nm", "Nú"],
            chapters=36,
        ),
        Book(
            id=5,
            name="Deuteronomio",
            abbrev="Deut",
            aliases=["De", "Dt"],
            chapters=34,
        ),
        Book(
            id=6,
            name="Josué",
            abbrev="Jos",
            aliases=[],
            chapters=24,
        ),
        Book(
            id=7,
            name="Jueces",
            abbrev="Jue",
            aliases=["Jc"],
            chapters=21,
        ),
        Book(
            id=8,
            name="Rut",
            abbrev="Rut",
            aliases=["Rt", "Ru"],
            chapters=4,
        ),
        Book(
            id=9,
            name="1 Samuel",
            abbrev="1 Sam",
            aliases=["1 Sa", "1 Sm"],
            chapters=31,
        ),
        Book(
            id=10,
            name="2 Samuel",
            abbrev="2 Sam",
            aliases=["2 Sa", "2 Sm"],
            chapters=24,
        ),
        Book(
            id=11,
            name="1 Reyes",
            abbrev="1 Rey",
            aliases=["1 Re"],
            chapters=22,
        ),
        Book(
            id=12,
            name="2 Reyes",
            abbrev="2 Rey",
            aliases=["2 Re"],
            chapters=22,
        ),
        Book(
            id=13,
            name="1 Crónicas",
            abbrev="1 Cró",
            aliases=["1 Cr"],
            chapters=29,
        ),
        Book(
            id=14,
            name="2 Crónicas",
            abbrev="2 Cró",
            aliases=["2 Cr"],
            chapters=36,
        ),
        Book(
            id=15,
            name="Esdras",
            abbrev="Esd",
            aliases=["Es"],
            chapters=10,
        ),
        Book(
            id=16,
            name="Nehemías",
            abbrev="Neh",
            aliases=["Ne"],
            chapters=13,
        ),
        Book(
            id=17,
            name="Ester",
            abbrev="Est",
            aliases=[],
            chapters=10,
        ),
        Book(
            id=18,
            name="Job",
            abbrev="Job",
            aliases=[],
            chapters=42,
        ),
        Book(
            id=19,
            name="Salmos",
            abbrev="Sal",
            aliases=[],
            chapters=150,
        ),
        Book(
            id=20,
            name="Proverbios",
            abbrev="Prov",
            aliases=["Pro", "Pr"],
            chapters=31,
        ),
        Book(
            id=21,
            name="Eclesiastés",
            abbrev="Ecl",
            aliases=["Qohelet", "Qoh", "Ec"],
            chapters=12,
        ),
        Book(
            id=22,
            name="Cantar de los Cantares",
            abbrev="Cant",
            aliases=[],
            chapters=8,
        ),
        Book(
            id=23,
            name="Isaías",
            abbrev="Isa",
            aliases=["Is"],
            chapters=66,
        ),
        Book(
            id=24,
            name="Jeremías",
            abbrev="Jer",
            aliases=["Jr", "Je"],
            chapters=52,
        ),
        Book(
            id=25,
            name="Lamentaciones",
            abbrev="Lam",
            aliases=["La"],
            chapters=5,
        ),
        Book(
            id=26,
            name="Ezequiel",
            abbrev="Ezeq",
            aliases=["Ez", "Ezq"],
            chapters=48,
        ),
        Book(
            id=27,
            name="Daniel",
            abbrev="Dan",
            aliases=["Da", "Dn"],
            chapters=12,
        ),
        Book(
            id=28,
            name="Oseas",
            abbrev="Os",
            aliases=[],
            chapters=14,
        ),
        Book(
            id=29,
            name="Joel",
            abbrev="Joel",
            aliases=["Joe", "Jol", "Jl"],
            chapters=3,
        ),
        Book(
            id=30,
            name="Amós",
            abbrev="Amós",
            aliases=["Amó", "Am"],
            chapters=9,
        ),
        Book(
            id=31,
            name="Abdías",
            abbrev="Abd",
            aliases=[],
            chapters=1,
        ),
        Book(
            id=32,
            name="Jonás",
            abbrev="Jonás",
            aliases=["Jon"],
            chapters=4,
        ),
        Book(
            id=33,
            name="Miqueas",
            abbrev="Miq",
            aliases=["Mi"],
            chapters=7,
        ),
        Book(
            id=34,
            name="Nahún",
            abbrev="Nah",
            aliases=["Na"],
            chapters=3,
        ),
        Book(
            id=35,
            name="Habacuc",
            abbrev="Hab",
            aliases=[],
            chapters=3,
        ),
        Book(
            id=36,
            name="Sofonías",
            abbrev="Sof",
            aliases=["So"],
            chapters=3,
        ),
        Book(
            id=37,
            name="Ageo",
            abbrev="Ag",
            aliases=[],
            chapters=2,
        ),
        Book(
            id=38,
            name="Zacarías",
            abbrev="Zac",
            aliases=["Za"],
            chapters=14,
        ),
        Book(
            id=39,
            name="Malaquías",
            abbrev="Mal",
            aliases=[],
            chapters=4,
        ),
    ],
)

DC = Library(
    id=210,
    name="Deuterocanonical",
    abbrev="DC",
    books=[
        Book(
            id=1,
            name="Tobías",
            abbrev="Tob",
            aliases=[],
            chapters=14,
        ),
        Book(
            id=2,
            name="Judit",
            abbrev="Jdt",
            aliases=[],
            chapters=16,
        ),
        Book(
            # TODO: Offsets: 11..16? Also sometimes letters (A..E)
            id=3,
            name="Additions to Esther",
            abbrev="Add Est",
            aliases=["Esg"], # "Esther Greek"
            chapters=10,
        ),
        Book(
            id=4,
            name="Sabiduría",
            abbrev="Sab",
            aliases=[],
            chapters=19,
        ),
        Book(
            id=5,
            name="Sirácides",
            abbrev="Sir",
            aliases=["Eclesiástico", "Si", "Eclo"],
            chapters=51,
        ),
        Book(
            id=6,
            name="Baruc",
            abbrev="Bar",
            aliases=["Ba"],
            chapters=6,
        ),
        Book(
            # TODO: This may be bound up in Baruch in certain editions
            id=7,
            name="Epistle of Jeremiah",
            abbrev="Ep Jer",
            aliases=["Letter of Jeremiah", "LJe"],
            chapters=1,
        ),
        Book(
            # TODO: This is sometimes within Daniel
            id=9,
            name="Prayer of Azariah",
            abbrev="Pr Azar",
            aliases=[],
            chapters=1,
        ),
        Book(
            # TODO: This is sometimes within Daniel
            id=10,
            name="Song of the Three Young Men",
            abbrev="Sg Three",
            aliases=["Song of the Three Youths", "S3Y"],
            chapters=1,
        ),
        Book(
            # TODO: This is sometimes within Daniel
            id=11,
            name="Susannah",
            abbrev="Sus",
            aliases=[],
            chapters=1,
        ),
        Book(
            # TODO: This is sometimes within Daniel
            id=12,
            name="Bel and the Dragon",
            abbrev="Bel",
            aliases=[],
            chapters=1,
        ),
        Book(
            id=13,
            name="1 Macabeos",
            abbrev="1 Mac",
            aliases=["1 Ma"],
            chapters=16,
        ),
        Book(
            id=14,
            name="2 Macabeos",
            abbrev="2 Mac",
            aliases=["2 Ma"],
            chapters=15,
        ),
    ],
)
# TODO: Rick Brannan did not provide complete data for this 'library' for Spanish
DC_ORTHODOX = Library(
    id=220,
    name="Deuterocanonical (Orthodox)",
    abbrev="DCO",
    books=[
        Book(
            id=1,
            name="1 Esdras",
            abbrev="1 Esd",
            aliases=["1 Es"],
            chapters=9,
        ),
        Book(
            id=2,
            name="Prayer of Manesseh",
            abbrev="Pr Man",
            aliases=[],
            chapters=1,
        ),
        Book(
            id=3,
            name="Psalm 151",
            abbrev="Ps 151",
            aliases=["Add Ps", "AddPs"],
            chapters=1,
        ),
        Book(
            id=4,
            name="3 Macabeos",
            abbrev="3 Mac",
            aliases=["3 Ma"],
            chapters=7,
        ),
        Book(
            id=5,
            name="2 Esdras",
            abbrev="2 Esd",
            aliases=["2 Es"],
            chapters=16,
        ),
        Book(
            id=6,
            name="4 Macabeos",
            abbrev="4 Mac",
            aliases=["4 Ma"],
            chapters=18,
        ),
    ],
)

NT = Library(
    id=400,
    name="Nuevo Testamento",
    abbrev="NT",
    books=[
        Book(
            id=1,
            name="Mateo",
            abbrev="Mat",
            aliases=["Mt"],
            chapters=28,
        ),
        Book(
            id=2,
            name="Marcos",
            abbrev="Mar",
            aliases=["Mc"],
            chapters=16,
        ),
        Book(
            id=3,
            name="Lucas",
            abbrev="Luc",
            aliases=["Lc"],
            chapters=24,
        ),
        Book(
            id=4,
            name="Juan",
            abbrev="Jn",
            aliases=[],
            chapters=21,
        ),
        Book(
            id=5,
            name="Hechos de los Apóstoles",
            abbrev="Hech",
            aliases=["Hch", "He"],
            chapters=28,
        ),
        Book(
            id=6,
            name="Romanos",
            abbrev="Rom",
            aliases=["Ro"],
            chapters=16,
        ),
        Book(
            id=7,
            name="1 Corintios",
            abbrev="1 Cor",
            aliases=["1 Co"],
            chapters=16,
        ),
        Book(
            id=8,
            name="2 Corintios",
            abbrev="2 Cor",
            aliases=["2 Co"],
            chapters=13,
        ),
        Book(
            id=9,
            name="Gálatas",
            abbrev="Gál",
            aliases=["Gá", "Gl"],
            chapters=6,
        ),
        Book(
            id=10,
            name="Efesios",
            abbrev="Efes",
            aliases=["Ef"],
            chapters=6,
        ),
        Book(
            id=11,
            name="Filipenses",
            abbrev="Fil",
            aliases=["Flp"],
            chapters=4,
        ),
        Book(
            id=12,
            name="Colosenses",
            abbrev="Col",
            aliases=[],
            chapters=4,
        ),
        Book(
            id=13,
            name="1 Tesalonicenses",
            abbrev="1 Tes",
            aliases=["1 Ts"],
            chapters=5,
        ),
        Book(
            id=14,
            name="2 Tesalonicenses",
            abbrev="2 Tes",
            aliases=["2 Ts"],
            chapters=3,
        ),
        Book(
            id=15,
            name="1 Timoteo",
            abbrev="1 Tim",
            aliases=["1 Ti"],
            chapters=6,
        ),
        Book(
            id=16,
            name="2 Timoteo",
            abbrev="2 Tim",
            aliases=["2 Ti"],
            chapters=4,
        ),
        Book(
            id=17,
            name="Tito",
            abbrev="Tit",
            aliases=["Tt", "Ti"],
            chapters=3,
        ),
        Book(
            id=18,
            name="Filemón",
            abbrev="Filem",
            aliases=["Flm"],
            chapters=1,
        ),
        Book(
            id=19,
            name="Hebreos",
            abbrev="Heb",
            aliases=[],
            chapters=13,
        ),
        Book(
            id=20,
            name="Santiago",
            abbrev="Sant",
            aliases=["Stgo", "St"],
            chapters=5,
        ),
        Book(
            id=21,
            name="1 Pedro",
            abbrev="1 Pe",
            aliases=["1 Ped"],
            chapters=5,
        ),
        Book(
            id=22,
            name="2 Pedro",
            abbrev="2 Pe",
            aliases=["2 Ped"],
            chapters=3,
        ),
        Book(
            id=23,
            name="1 Juan",
            abbrev="1 Juan",
            aliases=["1 Jn"],
            chapters=5,
        ),
        Book(
            id=24,
            name="2 Juan",
            abbrev="2 Juan",
            aliases=["2 Jn"],
            chapters=1,
        ),
        Book(
            id=25,
            name="3 Juan",
            abbrev="3 Juan",
            aliases=["3 Jn"],
            chapters=1,
        ),
        Book(
            id=26,
            name="Judas",
            abbrev="Judas",
            aliases=["Jds"],
            chapters=1,
        ),
        Book(
            id=27,
            name="Apocalipsis",
            abbrev="Apoc",
            aliases=["Ap"], 
            chapters=22,
        ),
    ],
)
